### ISSUE TITLE
Calling validate from the command line fails (missing directory)

### ISSUE THREAD

**Issue by msimonin** [msimonin/ombt-orchestrator#128]
https://github.com/msimonin/ombt-orchestrator/blob/432014ebf846f9931235ffccdd2945c29deba048/orchestrator/tasks.py#L551

We should maybe write: 

`kwargs.get("directory", BACKUP_DIR)`

**Comment by jrbalderrama** [comment]
the `directory` named var is set here https://github.com/msimonin/ombt-orchestrator/blob/master/orchestrator/campaign.py#L416

**Comment by msimonin** [comment]
it's not when using the cli
