### ISSUE TITLE
python-docker v3.0.0 makes docker_container fails

### ISSUE THREAD

**Issue by msimonin** [msimonin/ombt-orchestrator#50]
# Step to reproduce

`./cli.py deploy` (whatever the provider is)
`./cli.py test_case_1` (any option)

`ombt-controller` tasks fails when getting the benchmark result.

# Step to fix

The newest version of `python-docker` is `>=3.0.0`  seems to make the ansible `docker_container ` module fails. But here we don't constraint the installation to be `<3.0.0` (could use `2.7.0`).

https://github.com/msimonin/ombt-orchestrator/blob/143fe94ff65a9d06569fa24fc335cee461797849/ansible/roles/common/tasks/deploy.yml#L18-L23

and makes this fail: 

https://github.com/msimonin/ombt-orchestrator/blob/143fe94ff65a9d06569fa24fc335cee461797849/ansible/roles/ombt/tasks/deploy.yml#L17-L26

**Comment by msimonin** [comment]
btw I think we can remove the installation of `ìnfluxdb` pip package in the above snippet

**Comment by jrbalderrama** [comment]
We cannot remove `influxdb` it is required during deployment

**Comment by msimonin** [comment]
Yes indeed, it's used to create the initial database in infuxdb see:

https://github.com/msimonin/ombt-orchestrator/blob/c3337ee21e1475a8b196a25f773f16dde6ec0c3d/ansible/roles/influxdb/tasks/deploy.yml#L43-L47

Maybe one day we'll face the same issue as py-docker :)
