### ISSUE TITLE
Use mount module instead of cmd

### ISSUE THREAD

**Issue by jrbalderrama** [msimonin/ombt-orchestrator#52]
When executing the task 'mount' the following warning pops out:

`[WARNING]: Consider using mount module rather than running mount`

**Comment by msimonin** [comment]
Actually in #33, I suspect that we can remove this.
This seems to be legacy code inherited from the openstack deployment with EnOS

**Comment by jrbalderrama** [comment]
Indeed you can merge both tickets or declare this one as duplicate

**Comment by msimonin** [comment]
Duplicate of #33 :)
