### ISSUE TITLE
campaign-like but with incremental starts

### ISSUE THREAD

**Issue by msimonin** [msimonin/ombt-orchestrator#71]
Our current workflow is:

* given a set of parameters: params1, params2,...
* Deploy, bench with param_{i}, destroy and deploy, bench with params_{i+1}

In order to scale fast we probably wants to avoid destroying everything between two rounds.
I propose to start thinking/writing a campaign-like script that allows to incrementally scale a test_case.

**Comment by jrbalderrama** [comment]
a new option will be created for `campaign`: `--incremental`. This option will be set keeping the current configuration of the `conf.yaml` file. The logics for the test cases are:

- `test_case_1` performs a `zip`-like operation between `nbr_clients`, `nbr_servers`, and `pause`
- `test_case_2` deploys topics on demand

In both cases the difference of the current agents and total (required) agents are calculated at runtime

**Comment by msimonin** [comment]
👍
